### ISSUE TITLE
Remove the "FOR" from the MM scriptts

### ISSUE THREAD

**Issue by linuxgurugamer** [henrybauer/GPOSpeedPump#3]
Unneeded since the patches will be loaded with GPO, and can cause problems if left behind (FOR makes that mod known to MM)

**Comment by henrybauer** [comment]
I think there was originally a mismatch between the directory name and the mod name, but now the directory is "GPOSpeedFuelPump" so yeah, it's not needed.

**Comment by linuxgurugamer** [comment]
Ah, that makes sense.  Thank you
