### ISSUE TITLE
Replace the foreach

### ISSUE THREAD

**Issue by linuxgurugamer** [henrybauer/GPOSpeedPump#4]
Foreach is a bit inefficient.

Since the mod runs every tic/frame, try replacing this:

`foreach (Part shipPart in vessel.Parts) {`

with

```
for (int i = vessel.Parts.Count() - 1; i >= 0; i --)
{
Part shipPart = vessel.Parts[i];

```
and of course the other foreach's that are in the mod

**Comment by linuxgurugamer** [comment]
FYI, this was done in the PR I just submitted:
[#5](https://github.com/henrybauer/GPOSpeedPump/pull/5)

**Comment by henrybauer** [comment]
Thanks!  Will roll into next release
